from typing import List, Dict
from schemas.pipeline_schemas import ScriptOutput, HookOutput, HookOption


class HookGeneratorAgent:
    """
    Produces 5 hook variations per script for A/B testing.

    In Free Mode: generates 5 template hooks (deterministic).
    In Assist/Pro Mode: reuses hooks already generated by ScriptWriterAgent
    (passed via precomputed_hooks) so no extra Gemini calls are made.
    If a topic has no precomputed hooks, falls back to templates with a warning.
    """

    def __init__(
        self,
        generation_mode: str = "free",
        precomputed_hooks: Dict[str, List[HookOption]] = None,
    ) -> None:
        self.generation_mode = generation_mode
        self.precomputed_hooks: Dict[str, List[HookOption]] = precomputed_hooks or {}

    def _template_hooks(self, topic: str) -> List[HookOption]:
        return [
            HookOption(
                category="Curiosity",
                text=f"The hidden algorithm behind {topic} was finally exposed.",
            ),
            HookOption(
                category="Pain Point",
                text=f"Here is how {topic} saves 10 hours a week.",
            ),
            HookOption(
                category="Bold Claim",
                text=f"Traditional pipelines are dead. Welcome to the era of {topic}.",
            ),
            HookOption(
                category="Tutorial",
                text=f"How to build your first {topic} system in under 5 minutes.",
            ),
            HookOption(
                category="Mistake/Myth",
                text=f"The biggest misconception about {topic} is holding you back.",
            ),
        ]

    def generate_hooks(self, script: ScriptOutput) -> HookOutput:
        topic = script.topic

        if self.generation_mode != "free" and topic in self.precomputed_hooks:
            hooks = self.precomputed_hooks[topic]
            return HookOutput(topic=topic, hooks=hooks)

        if self.generation_mode != "free" and topic not in self.precomputed_hooks:
            print(
                f"[HookGenerator] No AI hooks cached for '{topic}' "
                "- using template hooks"
            )

        return HookOutput(topic=topic, hooks=self._template_hooks(topic))

    def process(self, scripts: List[ScriptOutput]) -> List[HookOutput]:
        return [self.generate_hooks(s) for s in scripts]
